### ISSUE TITLE
err: getting broadcast id

### ISSUE THREAD

**Issue by LoganCTanner** [SilverStar07/Twitch-EventSub-Full-Implementation#1]
I get the following error when going to https://api.twitch.tv/helix/streams?user_login=[username]

{"error":"Unauthorized","status":401,"message":"OAuth token is missing"}

**Comment by SilverStar07** [comment]
That error tends to happen when the config file isn't filled in with your Twitch API information or if you're not passing the Client-Id and Authorization in the API call headers. Also, make sure to replace [username] with your channel name without the square brackets. So for me it's https://api.twitch.tv/helix/streams?user_login=sirsilverstar . Just follow the instructions in the README, and you should be sorted. Let me know if anything in the instructions needs clarification.
